context:
  version: "3.0.0"

package:
  name: onefetch
  version: ${{ version }}

source:
  url: https://github.com/o2sh/onefetch/archive/${{ version }}.tar.gz
  sha256: 2877f2473120b41a33d03cc09bcded9ff4280951dfe447c1709df45b029e6e8b

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - onefetch --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Command-line Git information tool
  homepage: https://github.com/o2sh/onefetch
  repository: https://github.com/o2sh/onefetch

extra:
  recipe-maintainers:
    - danielnachun
