context:
  version: "2.26.1"

package:
  name: onefetch
  version: ${{ version }}

source:
  url: https://github.com/o2sh/onefetch/archive/${{ version }}.tar.gz
  sha256: ff43255d7c138c448cfdd1abacb01c6abe0c3e3886024e98ff077b28d4dc0ddc

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - onefetch --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Command-line Git information tool
  homepage: https://github.com/o2sh/onefetch
  repository: https://github.com/o2sh/onefetch

extra:
  recipe-maintainers:
    - danielnachun
