context:
  version: "2.27.1"

package:
  name: onefetch
  version: ${{ version }}

source:
  url: https://github.com/o2sh/onefetch/archive/${{ version }}.tar.gz
  sha256: 3a6f82d3da4da62b2e5406bbe307b0afc73cd8fcc4855534886d80ea0121cc03

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - onefetch --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Command-line Git information tool
  homepage: https://github.com/o2sh/onefetch
  repository: https://github.com/o2sh/onefetch

extra:
  recipe-maintainers:
    - danielnachun
