context:
  version: 2.22.0

package:
  name: onefetch
  version: ${{ version }}

source:
  url: https://github.com/o2sh/onefetch/archive/${{ version }}.tar.gz
  sha256: 1741516c628bb70b432285aa78439c4acfeb5df19e48b8d85dba5f71336e190b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - script:
      - onefetch --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Command-line Git information tool
  homepage: https://github.com/o2sh/onefetch
  repository: https://github.com/o2sh/onefetch

extra:
  recipe-maintainers:
    - danielnachun
